global:
  namespace: ns-connected-patient-experience

frontend:
  name: connected-patient-experience-app
  port: 80
  replicaCount: 1
  proxy:
    incomingPath: /connected-patient-experience-app/
    containerPath: "connected-patient-experience-app/"
  image:
    repository: gt-build.hdap.gatech.edu/connected-patient-experience
    tag: latest
    pullPolicy: Always
