global:
  namespace: ns-connected-patient-experience

frontend:
  name: connected-patient-experience-app
  port: 80
  replicaCount: 1
  proxy:
    incomingPath: /connected-patient-experience-app/
    containerPath: "/"
  image:
    repository: gt-build.hdap.gatech.edu/connected-patient-experience
    tag: latest
    pullPolicy: Always

backend:
  name: connected-patient-experience-backend
  port: 5000
  replicaCount: 1
  proxy:
    incomingPath: /connected-patient-experience-backend/
    containerPath: "/"
  image:
    repository: gt-build.hdap.gatech.edu/connected-patient-experience-backend
    tag: latest
    pullPolicy: Always
